var TEMPLATES = (function(TEMPLATES) {

    TEMPLATES.home = [
        '<img src="assets/home.png"><div class="home-icon folder">&nbsp;</div><div class="home-icon btn-apps">&nbsp;</div>'].join('');

    TEMPLATES.apps = [
        '<ul class="apps-list"><li><img src="assets/apps1.png"></li><li><img src="assets/apps2.png"></li></ul>'].join('');

    TEMPLATES.HPU_Contacts = [
        '<div id="header">                                                                             ',
        '    <div class="nav">',
        '        <i class="home">Home</i>                                                              ',
        '        <i class="favoris">Favoris</i>                                                        ',
        '        <i class="contact active">Contact</i>                                                 ',
        '        <i class="mail">Mail</i>                                                              ',
        '        <i class="multimedia">Contact</i>                                                     ',
        '   </div>',
        '   <i class="shadow-left hidden"></i>',
        '   <i class="shadow-right"></i>',
        '</div>                                                                                        ',
        '<div id="sub-header">                                                                         ',
        '    <span class="left">Groupe</span>                                                          ',
        '    <span class="center">Comptes</span>                                                       ',
        '    <span class="right">Options</span>                                                        ',
        '</div>',
        '<div id="carousel-groups" class="sub-header-box carousel"> ',
        '    <ul class="carousel-view">',
        '        <li>',
        '            <span class="group">',        
        '                <i class="bg-group"><i class="group-amis"></i></i>',
        '                Amis',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="group-maison"></i></i>',
        '                Famille',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="group-favoris"></i></i>',
        '                Favoris',
        '            </span>',
        '        </li>',
        '        <li>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="group-travail"></i></i>',
        '                Pro',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="group-sport"></i></i>',
        '                Sport',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="group-jeux"></i></i>',
        '                Jeux',
        '            </span>',
        '        </li>',
        '        <li>',
        '            <span class="btn">Créer</span>',
        '            <span class="btn">Gérer</span>',
        '        </li>',
        '    </ul>',
        '</div>',
        '<div id="carousel-accounts" class="sub-header-box carousel"> ',
        '    <ul class="carousel-view">',
        '        <li>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="account-facebook"></i></i>',
        '                Facebook',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="account-yahoo"></i></i>',
        '                Yahoo',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="account-gmail"></i></i>',
        '                Gmail',
        '            </span>',
        '        </li>',
        '        <li>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="account-bbox"></i></i>',
        '                BBox',
        '            </span>',
        '            <span class="group">',
        '                <i class="bg-group"><i class="account-hotmail"></i></i>',
        '                Hotmail',
        '            </span>',
        '        </li>',
        '        <li>',
        '            <span class="btn">Ajouter</span>',
        '            <span class="btn">Gérer</span>',
        '        </li>',
        '    </ul>',
        '</div>',
        '<div id="wrapper">                                                                            ',
        '    <div class="content" id="scroller">                                                       ',
        '        <ul id="thelist">                                                                     ',
        '        </ul>                                                                                 ',
        '    </div>                                                                                    ',
        '</div>                                                                                        ',
        '<div id="footer">                                                                             ',
        '    <i class="search">Search</i>                                                              ',
        '    <i class="plus">Add</i>                                                                   ',
        '    <span class="chronological active"><i></i>Dernier</span>                                  ',
        '    &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;                                         ',
        '    <span class="alphabetical"><i></i>A - Z</span>                                            ',
        '</div>                                                                                        '].join('');
        
    TEMPLATES.Contact_liste = [
        '<div id="header">                                                                             ',
        '    <h1 class="heading-1">CONTACTS</h1>                                                           ',
        '    <span class="btn btn-left">Retour</span>                                                  ',
        '</div>                                                                                        ',
        '                                                                                              ',
        '<div id="wrapper">                                                                            ',
        '    <div class="content" id="scroller">                                                                       ',
        '        <ul id="thelist">                                                                     ',
        '        </ul>                                                                                 ',
        '    </div>                                                                                    ',
        '</div>                                                                                        ',
        '<div id="footer">                                                                             ',
        '    <i class="search">Search</i>                                                              ',
        '    <i class="plus">Add</i>                                                                   ',
        '    <span class="chronological active"><i></i>Dernier</span>                                  ',
        '    &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;                                         ',
        '    <span class="alphabetical"><i></i>A - Z</span>                                            ',
        '</div>                                                                          '].join('');

    TEMPLATES.Page_minifiche = [
        '<div id="header">',
        '    <h1 class="heading-1">CONTACT</h1>',
        '    <span class="btn btn-left">Retour</span>',
        '    <span class="btn btn-right">Détail</span>',
        '</div>',
        '<div class="bg-blue resume" style="height:425px">',
        '    <span class="picture" style="background-image: url(layout/images/avatars/{{avatarBig}})"></span>',
        '    <span class="heading-1">{{nom}} {{prenom}}</span>',
        '    <i class="favorite"></i>',
        '    <div class="social">',
        '        <div class="quote">',
        '            Enfin en vacances ! Direction la Corse ! ',
        '            Plage et coppa !"',
        '        </div>',
        '        <div class="info"><i class="facebook"></i> Il y a 28 min</div>',
        '    </div>',
        '    <div class="actions">',
        '        <i class="btn-geo"></i>',
        '        <i class="btn-call"></i>',
        '        <i class="btn-mail"></i>',
        '    </div>',
        '</div>',
        '<div id="wrapper" style="top:500px">',
        '    <div class="content" id="scroller">',
        '        <ul id="thelist">',
        '            <li class="unread">',
        '                <span class="picture callin"></span>',
        '                <span class="heading-2">1 Appel émi</span>',
        '                <span class="date">18:06</span>',
        '            </li>',
        '            <li>',
        '                <span class="picture vocal"></span>',
        '                <span class="heading-2">1 Message vocal</span>',
        '                <span class="date">17:14</span>',
        '            </li>',
        '            <li>',
        '                <span class="picture yahoo"></span>',
        '                <span class="heading-2">Coucou !</span>',
        '                <span class="info">Bienvenue sur votre CV</span>',
        '                <span class="date">16:27</span>',
        '            </li>',
        '            <li>',
        '                <span class="picture facebook"></span>',
        '                <span class="heading-2">Demain</span>',
        '                <span class="info">N\'oublie pas mon livre stp.</span>',
        '                <span class="date">12:00</span>',
        '            </li>',
        '            <li>',
        '                <span class="picture callout"></span>',
        '                <span class="heading-2">1 appel manqué</span>',
        '                <span class="date">7:45</span>',
        '            </li>',
        '            <li>',
        '                <span class="picture sms"></span>',
        '                <span class="heading-2">1 SMS</span>',
        '                <span class="info">Je suis bien arrivé.</span>',
        '                <span class="date">Jeu.</span>',
        '            </li>',
        '            <li>',
        '                <span class="picture gmail"></span>',
        '                <span class="heading-2">Tr: Joyeux noel</span>',
        '                <span class="info">Je vous souhaite tous ...</span>',
        '                <span class="date">25/05/11</span>',
        '            </li>',
        '        </ul>',
        '    </div>',
        '</div>'].join('');


    TEMPLATES.Page_fiche = [
        '<div id="header">',
        '    <h1 class="heading-1">CONTACT</h1>',
        '    <span class="btn btn-left">Retour</span>',
        '    <span class="btn btn-right">Modifier</span>',
        '</div>',
        '<div id="notif">',
        '    <i class="delete"></i>',
        '    <span class="heading-3 white">Modifications enregistrées</span>',
        '</div>',        
        '<div class="actions">',
        '    <i class="btn-geo"></i>',
        '    <i class="btn-call"></i>',
        '    <i class="btn-mail"></i>',
        '</div>',
        '<div id="wrapper" class="bg-blue">',
        '    <div id="scroller" class="content resume">',
        '        <span class="picture" style="background-image: url(layout/images/avatars/{{avatarBig}})"></span>',
        '        <span class="heading-1">{{prenom}} {{nom}}</span>',
        '        <i class="favorite"></i>',
        '        <div class="fieldset">',
        '            <span class="label">Groupes</span>',
        '            <span class="field">',
        '                <i class="groups-edit"></i>',
        '                <i class="group-amis"></i>',
        '                <i class="group-sport"></i>',
        '            </span>',
        '            <hr />',
        '        </div>',
        '        <div class="fieldset">',
        '            <span class="label">Mobile</span>',
        '            <span class="field">+33 6 12 34 56 78</span>',
        '            <hr/>',
        '            <span class="label">Fixe</span>',
        '            <span class="field">+33 1 12 34 56 78</span>',
        '            <hr />',
        '            <span class="label">Email</span>',
        '            <span class="field">elsa.p@free.fr</span>',
        '            <hr />',
        '            <span class="label">Adresse</span>',
        '            <span class="field"><i class="geo-edit"></i>66, rue du faubourg Saint Martin. 75010 Paris</span>',
        '            <hr />',
        '            <span class="label">Site</span>',
        '            <span class="field">www.elsa-book.com</span>',
        '            <hr />',
        '        </div>',
        '        <div class="fieldset">',
        '            <span class="label"><i class="account-facebook"></i></span>',
        '            <span class="field">www.facebook.com/elsap...</span>',
        '            <hr/>',
        '            <span class="label"><i class="account-twitter"></i></span>',
        '            <span class="field">@elsap</span>',
        '            <hr />',
        '        </div>',
        '    </div>',
        '</div>'].join('');

    TEMPLATES.Page_fiche_edit_groupes = [
        '<div id="header">',
        '    <h1 class="heading-1">CONTACT</h1>',
        '    <span class="btn btn-left">Retour</span>',
        '    <span class="btn btn-right">Enregistrer</span>',
        '</div>',
        '<div id="wrapper" class="bg-blue">',
        '    <div id="scroller" class="content resume">',
        '        <span class="picture" style="background-image: url(layout/images/avatars/{{avatarBig}})"></span>',
        '        <span class="heading-1">{{prenom}} {{nom}}</span>',
        '        <h2 class="heading-3">Gerer les groupes</h2>',
        '        <div class="fieldset fieldset-groups">',
        '            <span class="label"><i class="group-sport"></i></span>',
        '            <span class="field"><i class="check check-sport"></i>Sport</span>',
        '            <hr/>',
        '            <span class="label"><i class="group-amis"></i></span>',
        '            <span class="field"><i class="check check-amis"></i>Amis</span>',
        '            <hr />',                            
        '            <span class="label"><i class="group-maison"></i></span>',
        '            <span class="field"><i class="check check-maison"></i>Maison</span>',
        '            <hr/>',
        '            <span class="label"><i class="group-travail"></i></span>',
        '            <span class="field"><i class="check check-travail"></i>Travail</span>',
        '            <hr />',                            
        '            <span class="label"><i class="group-jeux"></i></span>',
        '            <span class="field"><i class="check check-jeux"></i>Jeux</span>',
        '            <hr/>',                             
        '            <span class="label"><i class="group-internet"></i></span>',
        '            <span class="field"><i class="check check-internet"></i>Internet</span>',
        '            <hr />',
        '        </div>',
        '        <div class="fieldset fieldset-groups">',
        '            <span class="large"><i class="add"></i>Créer un nouveau groupe</span>',
        '        </div>',
        '        <span id="user-group-repository"></span>',
        '    </div>',
        '</div>'].join('');
        
    TEMPLATES.Page_fiche_edit = [
        '<div id="header">',
        '    <h1 class="heading-1">CONTACT</h1>',
        '    <span class="btn btn-left">Retour</span>',
        '    <span class="btn btn-right">Enregistrer</span>',
        '</div>',
        '<div id="wrapper" class="bg-blue" style="bottom:0">',
        '    <div id="scroller" class="content resume resume-edit">',
        '        <span class="picture" style="background-image: url(layout/images/avatars/{{avatarBig}})"></span>',
        '        <input type="text" name="firstname" class="firstname" value="{{prenom}}" />',
        '        <input type="text" name="lastname" class="lastname" value="{{nom}}" />',
        '        <div class="fieldset">',
        '            <span class="large">',
        '                <span class="float-right">',
        '                    <i class="group-amis"></i>',
        '                    <i class="group-sport"></i>',
        '                </span>',
        '                <span class="edit-groups">Gérer les groupes</span>',
        '                <div class="clear"></div>',
        '            </span>',
        '            <hr />',
        '        </div>',
        '        <div class="fieldset">',
        '            <span class="label"><span class="wrapper-label">Mobile</span></span>',
        '            <span class="field"><i class="delete"></i><input type="tel" name="mobile" value="+33 6 12 34 56 78" /></span>',
        '            <hr/>',
        '            <span class="label"><span class="wrapper-label">Fixe</span></span>',
        '            <span class="field"><i class="delete"></i><input type="tel" name="fixd" value="+33 1 12 34 56 78" /></span>',
        '            <hr />',
        '            <span class="label"><span class="wrapper-label">Email</span></span>',
        '            <span class="field"><i class="delete"></i><input type="email" name="mobile" value="elsa.p@free.fr"/></span>',
        '            <hr />',
        '            <span class="label"><span class="wrapper-label">Adresse</span></span>',
        '            <span class="field">',
        '                <i class="delete"></i>',
        '                <textarea name="addresse">66, rue du faubourg Saint Martin. 75010 Paris</textarea>',
        '            </span>',
        '            <hr />',
        '            <span class="label"><span class="wrapper-label">Site</span></span>',
        '            <span class="field"><i class="delete"></i><input type="url" name="mobile" value="www.elsa-book.com" /></span>',
        '            <hr />',
        '        </div>',
        '        <div class="fieldset">',
        '            <span class="label"><i class="account-facebook"></i></span>',
        '            <span class="field"><i class="delete"></i><input type="email" name="fb" value="www.facebook.com/elsap" /></span>',
        '            <hr/>',
        '            <span class="label"><i class="account-twitter"></i></span>',
        '            <span class="field"><i class="delete"></i><input type="email" name="twitter" value="@elsap" /></span>',
        '            <hr />',
        '        </div>',
        '    </div>',
        '</div>'].join('');

    return TEMPLATES;

})(TEMPLATES || {});